import {
  LayoutDashboard,
  Bot,
  ClipboardCheck,
  Search,
  Bell,
  Plus,
  ArrowLeft,
  UploadCloud,
  FileText,
  Trash2,
  PlayCircle,
  Sparkles,
  Eye,
  EyeOff,
  Users,
  MessageSquare,
  BarChart2,
  ChevronRight,
  Settings,
  Lock,
  LoaderCircle,
  CheckCircle2,
  Volume2,
  UsersRound,
  Globe,
  ChevronDown,
  BookCopy,
  BrainCircuit,
  Crop,
  RotateCw,
  X,
  WandSparkles,
  ShieldCheck,
  FileBarChart2,
  Clock,
  Download,
  Cpu,
  Send,
  Copy,
  Link,
  Menu,
  Presentation,
  ClipboardList,
  Languages,
  UserCog,
  HelpCircle,
  LogOut,
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  bot: Bot,
  tasks: ClipboardCheck,
  search: Search,
  bell: Bell,
  add: Plus,
  back: ArrowLeft,
  upload: UploadCloud,
  file: FileText,
  delete: Trash2,
  play: PlayCircle,
  sparkles: Sparkles,
  visible: Eye,
  hidden: EyeOff,
  users: Users,
  chat: MessageSquare,
  chart: BarChart2,
  right: ChevronRight,
  settings: Settings,
  lock: Lock,
  loading: LoaderCircle,
  success: CheckCircle2,
  voice: Volume2,
  classes: UsersRound,
  language: Globe,
  down: ChevronDown,
  task: BookCopy,
  brain: BrainCircuit,
  crop: Crop,
  rotate: RotateCw,
  close: X,
  wand: WandSparkles,
  shieldCheck: ShieldCheck,
  report: FileBarChart2,
  clock: Clock,
  download: Download,
  cpu: Cpu,
  send: Send,
  copy: Copy,
  link: Link,
  menu: Menu,
  presentation: Presentation,
  clipboardList: ClipboardList,
  languages: Languages,
  userCog: UserCog,
  helpCircle: HelpCircle,
  logOut: LogOut,
};