// System-owned interface copy. User-authored content must not be looked up here.
export const englishUi: Record<string, string> = {
  "請填寫學校及聯絡資料。": "Enter your school and contact details.",
  "每次最多提交 10 個角色；如需更多，可另外提交一批。": "Submit up to 10 characters per request. For more, submit another batch.",
  "領航者 (Navigator)": "Navigator",
  "探索者 (Explorer)": "Explorer",
  "啟航者 (Voyager)": "Voyager",
  "練習者 (Builder)": "Builder",
  "表現非常出色，你已經穩穩掌握這次的核心知識。": "Excellent work! You have a strong grasp of the core concepts.",
  "整體掌握得不錯，再多一點練習就能更上一層樓。": "Good understanding overall. A little more practice will take you further.",
  "別氣餒！這是學習的必經過程，我們再複習一下核心概念吧。": "Keep going! This is part of learning. Let's review the core concepts together.",
  "先把基礎打穩，我們一步一步把這次的知識補起來。": "Let's build a strong foundation and work through these concepts step by step.",
  "免費版只能完成並發布 1 個角色。": "The free plan includes one published character.",
  "免費版只能建立 1 個角色，請升級到付費版。": "The free plan includes one character. Upgrade to create more.",
  "免費版的角色形象 AI 生成功能已用完，請升級到付費版。": "Your free AI avatar allowance is used up. Please upgrade.",
  "免費版的背景 AI 生成功能已用完，請升級到付費版。": "Your free AI background allowance is used up. Please upgrade.",
  "免費版聲音預覽次數已用完，請升級到付費版。": "Your free voice preview allowance is used up. Please upgrade.",
  "免費版影片工作室生成次數已用完，請升級到付費版。": "Your free Video Studio allowance is used up. Please upgrade.",
  "免費版對話次數已用完，請升級到付費版。": "Your free conversation allowance is used up. Please upgrade.",
  "免費版語音功能已用完，請升級到付費版。": "Your free voice allowance is used up. Please upgrade.",
  "功能使用次數不足": "Insufficient feature allowance",
  "形象 AI 生成": "AI Avatar Generation",
  "背景 AI 生成": "AI Background Generation",
  "聲音預覽": "Voice Preview",
  "語音回覆次數": "Voice Replies",
  "測驗": "Quiz",
  "批改狀態": "Grading Status",
  "總得分": "Total Score",
  "得分百分比": "Score Percentage",
  "題號": "Question Number",
  "題目": "Question",
  "學生答案": "Student Answer",
  "正確答案": "Correct Answer",
  "題目滿分": "Maximum Question Score",
  "是否正確": "Correct",
  "AI 評語": "AI Feedback",
  "異常標記": "Alerts",
  "是": "Yes",
  "否": "No",
  "批改成果": "Grading Results",
  "移除 {0}": "Remove {0}",
  "班級：{0}": "Classes: {0}",
  "學生人數：約 {0} 人": "Students: approximately {0}",
  "使用時段：{0}": "Usage period: {0}",
  "角色背景：{0}": "Character background: {0}",
  "補充需求：{0}": "Additional requirements: {0}",
  "角色 {0}": "Character {0}",
  "已更新 {0} 使用次數（上限 {1}）": "Updated {0} usage (limit {1})",
  "已更新 {0} 上限": "Updated {0} limit",
  "{0} 已用": "{0} used",
  "{0} 上限": "{0} limit",
  "{0} 月 {1} 日": "{0}/{1}",
  "已連續學習 {0} 天，再堅持 {1} 天解鎖下一個里程碑！": "You've learned for {0} consecutive days. Keep going for {1} more to unlock the next milestone!",
  "API 回傳格式錯誤（{0} {1}）": "Invalid API response ({0} {1})",
  "{0} 待機動畫": "{0} idle animation",
  "嗨，{0}！": "Hi, {0}!",
  "今日互動 {0} 次": "{0} interactions today",
  "今天 {0}:{1}": "Today {0}:{1}",
  "「{0}」有新測試「{1}」等你挑戰！": "{0} has a new quiz, “{1}”, for you!",
  "{0} 分享了新的 AI Bot「{1}」給你": "{0} shared a new AI bot, “{1}”, with you",
  "已加入學生 {0}": "Added student {0}",
  "「{0}」刪除後無法復原，相關作答與批改資料也會一併移除。": "Deleting “{0}” cannot be undone. Related responses and grades will also be removed.",
  "刪除測驗 {0}": "Delete quiz {0}",
  "開啟「{0}」選單": "Open menu for “{0}”",
  "全部學生 ({0})": "All Students ({0})",
  "未完成 ({0})": "Incomplete ({0})",
  "已完成 ({0})": "Completed ({0})",
  "進行中 ({0})": "In Progress ({0})",
  "{0} 已用完": "{0} allowance used up",
  "剩餘：{0}{1}": "Remaining: {0}{1}",
  "/ 總額：{0}{1}": "/ Total: {0}{1}",
  "本月 AI 算力剩餘 {0}%，預計 {1} 重置": "{0}% of monthly AI allowance remaining. Resets {1}",
  "開啟 {0}": "Open {0}",
  "聊天請求失敗：{0}": "Chat request failed: {0}",
  "創建角色 {0}": "Characters created: {0}",
  "尚有未完成步驟，請先完成第 {0} 步。": "Some steps are incomplete. Complete step {0} first.",
  "機器人角色席位已用完（{0}）。PRO 用戶可洽客服快速加開席位。": "All character slots are used ({0}). PRO users can contact support for more slots.",
  "沒有名稱包含「{0}」的機器人": "No bots with names containing “{0}”",
  "主題已由「{0}」切換為「{1}」": "Topic switched from “{0}” to “{1}”",
  "目前主題：{0}": "Current topic: {0}",
  "確定要刪除 {0} 個對話嗎？": "Delete {0} conversations?",
  "刪除 {0} 項": "Delete {0} Items",
  "已從歷史紀錄中移除 {0} 個對話。": "Removed {0} conversations from history.",
  "相機未啟用：{0}": "Camera not enabled: {0}",
  "切換 AI 回覆至{0}": "Switch AI replies to {0}",
  "正在生成 {0} 動畫": "Generating {0} animation",
  "等待 {0} 動畫": "Waiting for {0} animation",
  "正在生成：{0} 原始視頻...": "Generating original {0} video…",
  "正在重試：{0}（第 {1} 次）...": "Retrying {0} (attempt {1})…",
  "正在恢復：{0} 原始視頻...": "Restoring original {0} video…",
  "{0} 生成失敗": "{0} generation failed",
  "{0} 生成等待超時（約 {1} 分鐘）": "{0} generation timed out (approximately {1} minutes)",
  "{0}背景": "{0} background",
  "文件：{0}": "File: {0}",
  "{0} 無限制": "{0} Unlimited",
  "已儲存「{0}」。": "Saved “{0}”.",
  "刪除「{0}」？": "Delete “{0}”?",
  "已刪除「{0}」。": "Deleted “{0}”.",
  "語文（中文）": "Chinese Language",
  "英文": "English",
  "數學": "Mathematics",
  "科學": "Science",
  "科技/編程": "Technology / Coding",
  "常識/人文": "General Studies / Humanities",
  "藝術/其他": "Arts / Other",
  "chinese": "Chinese Language",
  "english": "English",
  "math": "Mathematics",
  "science": "Science",
  "tech": "Technology / Coding",
  "humanities": "General Studies / Humanities",
  "other": "Other",
  "教學指揮艙": "Command Center",
  "智能評測": "Smart Assessment",
  "AI 機器人工作坊": "AI Bot Workshop",
  "學生與 Bot 分享": "Share with Students",
  "ChopReality 首頁": "ChopReality Home",
  "系統更新中": "System update in progress",
  "新版本部署完成後將自動恢復": "Service will resume automatically when deployment is complete",
  "網路連線不穩，正在重新連線…": "Network unstable, reconnecting…",
  "正在載入…": "Loading…",
  "申請管理": "Avatar Requests",
  "搜尋 AI 機器人名稱…": "Search AI bot name…",
  "全域搜尋...": "Search…",
  "你沒有權限查看此頁面。": "You do not have permission to view this page.",
  "學生": "Student",
  "老師": "Teacher",
  "管理員": "Administrator",
  "登入狀態已失效，請重新登入": "Your session has expired. Please sign in again.",
  "帳戶資料更新失敗": "Could not update your account",
  "預覽模式未提供此功能，請在正式環境重試。": "This feature is unavailable in preview mode. Please try in the live environment.",
  "請輸入目前密碼": "Enter your current password",
  "新密碼至少 8 個字元": "Your new password must contain at least 8 characters",
  "兩次輸入的新密碼不一致": "The new passwords do not match",
  "密碼已更新": "Password updated",
  "密碼修改失敗": "Could not update password",
  "請輸入有效的電郵地址": "Enter a valid email address",
  "請輸入目前密碼確認": "Enter your current password to confirm",
  "電郵已更新": "Email updated",
  "電郵更改失敗": "Could not update email",
  "已套用主題（預覽模式僅保存在本機）": "Theme applied (saved locally in preview mode)",
  "主題設定保存失敗": "Could not save theme settings",
  "頭像上傳失敗": "Could not upload avatar",
  "帳戶資料已更新": "Account updated",
  "重置使用次數失敗": "Could not reset usage",
  "免費功能使用次數已重置": "Free feature usage has been reset",
  "帳戶中心": "Account Center",
  "更新你的頭像、用戶名和帳戶基本資料。": "Update your avatar, username, and account details.",
  "更新你的頭像、名字和帳戶基本資料。": "Update your avatar, name, and account details.",
  "返回工作台": "Back to Workspace",
  "PRO 方案説明": "PRO Plan Details",
  "頭像": "Avatar",
  "上傳中...": "Uploading…",
  "上傳照片": "Upload Photo",
  "默認頭像": "Default Avatar",
  "用戶名": "Username",
  "名字": "Name",
  "電郵": "Email",
  "角色": "Role",
  "套餐": "Plan",
  "重置中...": "Resetting…",
  "重置使用次數": "Reset Usage",
  "儲存中...": "Saving…",
  "儲存帳戶資料": "Save Account Details",
  "安全設定": "Security Settings",
  "修改密碼": "Change Password",
  "目前密碼": "Current password",
  "新密碼（至少 8 個字元）": "New password (at least 8 characters)",
  "確認新密碼": "Confirm new password",
  "新密碼至少 8 個字元。": "Your new password must contain at least 8 characters.",
  "更新中...": "Updating…",
  "更新密碼": "Update Password",
  "更改郵箱": "Change Email",
  "新電郵地址": "New email address",
  "更改郵箱需要輸入目前密碼確認。": "Enter your current password to confirm your email change.",
  "更新電郵": "Update Email",
  "外觀": "Appearance",
  "選擇工作台的主題模式。": "Choose a theme for your workspace.",
  "明亮": "Light",
  "深色": "Dark",
  "聯絡我們": "Contact Us",
  "如果你希望提供產品意見、瞭解付費方案，或購買我們的機器人創建服務，可以直接聯絡我們。": "Contact us to share feedback, learn about paid plans, or purchase our bot creation service.",
  "我知道了": "Got It",
  "創建角色已用完": "Character creation limit reached",
  "未命名測驗": "Untitled Quiz",
  "未命名題庫": "Untitled Question Bank",
  "刪除草稿失敗": "Could not delete draft",
  "返回智能評測": "Back to Smart Assessment",
  "多維度 AI 異常警示展示": "Multi-dimensional AI Alert Demo",
  "運用 AI 技術快速生成測驗，並自動批改與分析學生表現。": "Quickly create assessments with AI, automatically grade work, and analyze student performance.",
  "AI 警示展示": "AI Alert Demo",
  "AI 智能出題": "AI Question Generator",
  "上傳教材或輸入主題，AI 將自動為您生成選擇題、填充題與問答題，大幅節省備課時間。": "Upload materials or enter a topic to generate multiple-choice, fill-in-the-blank, and written-response questions with AI.",
  "創建新測驗": "Create Quiz",
  "12 份待批改": "12 awaiting grading",
  "智能批改工作台": "Smart Grading Workspace",
  "AI 輔助批改主觀題與作文，自動生成評語與得分建議，大幅提升批改效率。": "Use AI to grade written responses and essays, with suggested feedback and scores.",
  "進入批改": "Start Grading",
  "草稿箱": "Drafts",
  "份": "items",
  "正在載入草稿...": "Loading drafts…",
  "草稿": "Draft",
  "題": "questions",
  "還沒有草稿": "No drafts yet",
  "歷史題庫": "Question Bank History",
  "查看全部": "View All",
  "正在載入題庫...": "Loading question banks…",
  "題庫": "Question Bank",
  "題已收錄": "questions saved",
  "剛剛更新": "Just updated",
  "還沒有題庫，先到測驗預覽把題目加入題庫吧。": "No question banks yet. Add questions from the quiz preview to get started.",
  "請輸入電郵。": "Enter your email.",
  "請輸入密碼。": "Enter your password.",
  "登入服務暫時不可用。": "Sign-in is temporarily unavailable.",
  "登入服務回傳格式異常。": "Invalid response from the sign-in service.",
  "這不是學生帳戶，請選擇教師登入。": "This is not a student account. Please select teacher sign-in.",
  "這是學生帳戶，請選擇學生登入。": "This is a student account. Please select student sign-in.",
  "登入成功，正在進入學生平台...": "Signed in. Opening the student platform…",
  "登入成功，正在進入教師工作台...": "Signed in. Opening the teacher workspace…",
  "專為學習而設": "Designed for Learning",
  "Chopreality 是一個無需編程的AI 藝術創作平台，讓師生在零基礎下也能輕鬆一站式創作不同AI作品，製作出用於教學或展示的互動作品。": "ChopReality is a no-code AI art platform where teachers and students can easily create interactive AI projects for teaching and presentations.",
  "歡迎回來": "Welcome Back",
  "選擇你的身份，進入專屬學習空間。": "Choose your role to enter your learning space.",
  "登入方式": "Sign-in Method",
  "教師登入": "Teacher Sign-in",
  "學生登入": "Student Sign-in",
  "密碼": "Password",
  "記住我": "Remember me",
  "提交中...": "Submitting…",
  "進入學生平台": "Enter Student Platform",
  "進入教師工作台": "Enter Teacher Workspace",
  "角色不存在": "Character not found",
  "角色載入失敗": "Could not load character",
  "正在載入角色…": "Loading character…",
  "歡迎回到教學指揮艙，和學生們一起開啟今天的學習之旅！": "Welcome back to the Command Center. Start today's learning journey with your students!",
  "早安": "Good morning",
  "午安": "Good afternoon",
  "下午好": "Good afternoon",
  "晚上好": "Good evening",
  "夜深了": "It's getting late",
  "不夠 Token 怎麼辦？": "What if I run out of tokens?",
  "Token 是你與 AI 夥伴對話的額度，用完後暫時無法繼續對話。你可以聯絡客服專員為你調整方案或補充額度": "Tokens are your allowance for chatting with AI buddies. If you run out, contact support to adjust your plan or add more.",
  "為何我的機器人沒有顯示測試題？": "Why does my bot not show a quiz?",
  "如果夥伴卡片上沒有「測試題」標籤，代表老師尚未為這隻機器人配置測驗，可以手動刷新網頁或聯繫客服專員查詢。": "If a buddy card has no Quiz badge, your teacher has not assigned a quiz to it yet. Refresh the page or contact support for help.",
  "怎麼查看我的 Token 用量？": "How can I check my token usage?",
  "學生首頁右上角的 Tokens 數字就是你的剩餘額度（剩餘 / 每月總額）。點擊旁邊的「？」圖示可以查看詳細說明。": "The Tokens counter at the top right of the student home page shows your remaining and monthly allowance. Select the question-mark icon for details.",
  "如何更換頭像或修改個人資料？": "How do I change my avatar or profile?",
  "點擊右上角頭像 → 帳戶中心，即可編輯頭像、用戶名，並在「安全設定」中修改密碼或電郵。": "Select your avatar at the top right, then Account Center to edit your avatar and username. Change your password or email under Security Settings.",
  "如何更改密碼？": "How do I change my password?",
  "帳戶中心 → 安全設定 → 修改密碼，輸入目前密碼與新密碼（至少 8 個字元）即可完成更新。": "Go to Account Center, Security Settings, then Change Password. Enter your current password and a new password with at least 8 characters.",
  "不夠對話次數怎麼辦": "What if I run out of conversations?",
  "對話次數是你與 AI 夥伴互動的額度，用完後暫時無法繼續對話。你可以聯絡客服專員為你調整方案或補充額度": "Conversations are your allowance for interacting with AI buddies. Contact support to adjust your plan or top up when you run out.",
  "如果夥伴卡片上沒有「測試題」標籤，代表你尚未為這隻機器人配置測驗，可以手動刷新網頁或聯繫客服專員查詢。": "If a buddy card has no Quiz badge, you have not assigned a quiz to it yet. Refresh the page or contact support for help.",
  "怎麼查看我的對話次數用量？": "How do I check my conversation usage?",
  "點擊教師首頁右上角使用次數，這裡就是你的目前使用額度": "Select the usage counter at the top right of the teacher home page to view your current allowance.",
  "聯絡電話": "Phone",
  "官方電郵": "Official Email",
  "幫助中心": "Help Center",
  "常見問題與聯絡方式": "Frequently asked questions and contact information",
  "了解方案內容與權益": "Learn about your plan and benefits",
  "查看方案説明": "View Plan Details",
  "如何製作數字人？": "How do I create a digital avatar?",
  "學生如何應用？": "How can students use the platform?",
  "如何智能批改？": "How does smart grading work?",
  "如何運用 AI 創建新測驗？": "How do I create a quiz with AI?",
  "返回帳戶中心": "Back to Account Center",
  "PRO 方案": "PRO Plan",
  "您的 PRO 方案已啟用": "Your PRO Plan Is Active",
  "以下是這次服務的內容、可使用的範圍，以及遇到問題時可以怎麼找我們協助。": "Here is what your service includes, where you can use it, and how to get help.",
  "方案內容": "Plan Features",
  "專屬數字人角色": "Custom Digital Avatar",
  "為學校度身設計及製作 1 個 ChopReality 數字人角色，包括基本形象與技術設定。": "One custom ChopReality digital avatar designed for your school, including its appearance and technical setup.",
  "12 個月使用權": "12-month Access",
  "由啟用日期起計 12 個月，老師可全年按教學需要自行更新內容並重複使用同一角色。": "Use the same character for 12 months from activation and update its content throughout the school year.",
  "首次設定協助": "Initial Setup Support",
  "協助完成首次設定及示範應用流程，確保可於校內順利使用。": "We help with initial setup and demonstrate the workflow so your school can get started smoothly.",
  "可使用範圍": "Permitted Use",
  "數字人角色及相關設定，於授權期內可用於校內教學活動、校本課程及校內宣傳。如需用於對外公開宣傳或大型公開活動，歡迎與我們聯繫，另行討論合適的授權安排。": "During the license period, the avatar and its settings may be used for school teaching, school-based curricula, and internal promotion. Contact us to discuss licensing for public promotion or large public events.",
  "教師培訓與支援": "Teacher Training and Support",
  "一次 1 小時的教學工作坊，之後也可隨時查詢": "One 1-hour teaching workshop, with ongoing support afterward",
  "教學工作坊（1 小時）": "Teaching Workshop (1 Hour)",
  "對象：相關科任老師／IT 及課程負責老師": "For subject teachers, IT staff, and curriculum coordinators",
  "內容：帳戶及專案基本操作示範、數字人內容更新流程": "Covers account and project basics and updating digital avatar content",
  "日常技術諮詢": "Ongoing Technical Support",
  "實際使用中如有操作或設定上的問題，可透過電郵／訊息查詢，我們會在辦公時間內回覆並提供指導。": "Email or message us with questions about operation or setup. We respond during office hours with guidance.",
  "教學影片": "Video Tutorials",
  "觀看 →": "Watch →",
  "認識 ChopReality": "About ChopReality",
  "由香港理工大學碩士生團隊開發，結合 AI 與沉浸式互動學習，提升教與學體驗": "Developed by a Hong Kong Polytechnic University master's student team, combining AI and immersive interactive learning.",
  "教師端": "For Teachers",
  "快速創建 AI 學科數字人、分析學生互動與學習難點，並運用 AI 輔助設計測驗。": "Create AI subject avatars, analyze student interactions and learning difficulties, and design quizzes with AI.",
  "學生端": "For Students",
  "與 AI 數字人即時對話，透過探索式學習加深理解與應用能力。": "Chat with AI avatars in real time and develop understanding and application skills through exploration.",
  "粵語／英語／普通話即時切換": "Switch between Cantonese, English, and Mandarin",
  "繁體中文介面": "Traditional Chinese Interface",
  "數據驅動教學": "Data-informed Teaching",
  "有任何問題？我們隨時協助": "Questions? We Are Here to Help",
  "聯絡客服": "Contact Support",
  "中國語文": "Chinese Language",
  "中國歷史 · 歷史科": "Chinese History · History",
  "英國語文 (English Language)": "English Language",
  "數學科 · 邏輯思維": "Mathematics · Logical Thinking",
  "小學常識科 · 跨學科": "Primary General Studies · Cross-curricular Learning",
  "科學 · STEM · 創科教育": "Science · STEM · Innovation Education",
  "公民與社會發展科 (CS) · 德育及公民教育": "Citizenship and Social Development · Moral and Civic Education",
  "SEN 特殊教育 · 社交與情緒共融": "Special Educational Needs · Social and Emotional Inclusion",
  "校園導覽 · 圖書館 · 升學規劃": "School Tours · Library · Further Education Planning",
  "Pixar 3D 立體風格": "Pixar-style 3D",
  "生動具科技感，學生最喜愛": "Lively and futuristic, popular with students",
  "迪士尼／繪本插畫風格": "Disney / Picture-book Illustration",
  "親切溫暖，特別適合小學及 SEN 共融": "Warm and friendly, ideal for primary schools and SEN inclusion",
  "國風水墨／經典寫實風格": "Chinese Ink / Classical Realism",
  "典雅莊重，適合歷史人物與中華文化": "Elegant and dignified, ideal for historical figures and Chinese culture",
  "校內專屬吉祥物／既有角色客製": "Custom School Mascot / Existing Character",
  "依校徽、吉祥物或既有角色參考圖客製": "Customize from a school emblem, mascot, or character reference",
  "課堂中使用": "During Class",
  "課後／自主學習": "After Class / Independent Learning",
  "課堂中與課後皆使用": "During and After Class",
  "跨學科教學": "Cross-curricular Teaching",
  "由製作團隊按角色定位建議": "Let the production team recommend based on the character",
  "（選填）": "(Optional)",
  "暫時未能提交，請稍後再試。": "Could not submit. Please try again later.",
  "已收到": "Received",
  "返回 ChopReality": "Back to ChopReality",
  "學校專屬 · AI 數字人客製化配置通道": "School-exclusive AI Avatar Customization",
  "填寫使用情境與背景資料後，AI 會先生成詳細角色設定草案。老師確認後，ChopReality 團隊才會正式開始製作。": "Provide your teaching context and background information to generate a detailed AI character draft. Production begins after you confirm it.",
  "填寫需求": "Enter Requirements",
  "AI 生成草案": "Generate AI Draft",
  "確認並提交": "Confirm and Submit",
  "已收到貴校的需求": "We Have Received Your School's Request",
  "參考編號": "Reference Number",
  "。目前已使用": ". Used:",
  "個額度，剩餘": "credits; remaining:",
  "個額度。": "credits.",
  "繼續提交下一批": "Submit Another Batch",
  "本次已提交角色": "Characters Submitted",
  "團隊會以老師確認的設定草案為製作依據。": "Production will follow the character drafts confirmed by the teacher.",
  "已提交": "Submitted",
  "學校與聯絡資料": "School and Contact Details",
  "先查詢學校可用額度，再開始配置角色。": "Check your school's available allowance before configuring characters.",
  "學校名稱": "School Name",
  "請輸入學校全名": "Enter the full school name",
  "查詢中": "Checking…",
  "查詢額度": "Check Allowance",
  "聯絡老師": "Contact Teacher",
  "老師姓名": "Teacher's name",
  "電話／WhatsApp": "Phone / WhatsApp",
  "例如：9123 4567": "e.g. 9123 4567",
  "聯絡電郵": "Contact Email",
  "本學年客製化額度": "Customization Allowance for This School Year",
  "剩餘": "Remaining",
  "已使用": "Used",
  "個額度，本批最多可提交": "credits; maximum for this batch:",
  "個角色。": "characters.",
  "2. 角色需求": "2. Character Requirements",
  "每個角色均需生成並確認一份設定草案。": "Generate and confirm a configuration draft for each character.",
  "個": "items",
  "新增下一個角色": "Add Another Character",
  "已達本次可用額度上限。如需更多角色，請聯絡 ChopReality 團隊。": "You have reached your available allowance. Contact the ChopReality team for more characters.",
  "提交本次需求": "Submit Request",
  "上傳內容只供本次數字人配置使用，請勿包含學生個人資料或未獲授權內容。": "Uploads are used only for this avatar configuration. Do not include students' personal information or unauthorized content.",
  "正在提交…": "Submitting…",
  "請先為每個角色生成 AI 設定草案，並完成確認後再提交。": "Generate and confirm an AI configuration draft for each character before submitting.",
  "請先填妥學校及聯絡資料。": "Complete the school and contact details first.",
  "已確認設定": "Configuration Confirmed",
  "欄位已鎖定，返回修改後可再次編輯。": "Fields are locked. Go back to edit them.",
  "填妥必填欄位後生成 AI 草案。": "Complete the required fields to generate an AI draft.",
  "移除": "Remove",
  "數字人名稱／角色主題": "Avatar Name / Character Topic",
  "例如：蘇軾／英文對話大使 Sophie／校園吉祥物": "e.g. Su Shi / Sophie the English Conversation Ambassador / School Mascot",
  "預計使用班級": "Target Classes",
  "例如：4A、4B": "e.g. 4A, 4B",
  "學生人數（約數）": "Approximate Number of Students",
  "例如：60": "e.g. 60",
  "使用時段": "Usage Period",
  "課後／自主學習使用": "After-class / Independent Learning Use",
  "應用學科（可多選）": "Subjects (Select Multiple)",
  "其他自訂學科": "Other Custom Subject",
  "角色視覺風格偏好（可多選）": "Visual Style Preferences (Select Multiple)",
  "推薦": "Recommended",
  "上傳吉祥物／校徽圖片": "Upload Mascot / School Emblem",
  "點擊上傳 JPG／PNG": "Click to upload JPG / PNG",
  "教學文檔／單元教材": "Teaching Documents / Unit Materials",
  "點擊或拖入教材": "Click or drop teaching materials",
  "支援 PDF、Word、PPT；單一檔案上限 20MB，全部檔案合計上限 60MB。": "PDF, Word, and PPT supported. Maximum 20 MB per file and 60 MB total.",
  "或直接貼上課文、單元內容或知識點文字…": "Or paste lesson text, unit content, or key concepts…",
  "角色背景資料": "Character Background",
  "請簡述角色身份、背景故事、性格取向或需參考的人設資料": "Describe the character's identity, story, personality, or reference background",
  "補充需求": "Additional Requirements",
  "例如：希望多用廣東話反問句引導思考、採用半身視角…": "e.g. Use Cantonese questions to guide thinking; show the character from the waist up…",
  "AI 生成詳細角色設定": "Generate Detailed AI Character Configuration",
  "AI 正在整理角色定位、語氣與教學範圍…": "AI is organizing the character's role, tone, and teaching scope…",
  "AI 角色設定草案": "AI Character Configuration Draft",
  "返回修改": "Back to Edit",
  "確認角色設定": "Confirm Character Configuration",
  "重新編輯設定": "Edit Configuration Again",
  "請先填寫角色名稱、班級、學生人數及背景資料。": "Enter the character's name, classes, student count, and background first.",
  "新申請": "New Requests",
  "處理中": "In Progress",
  "已完成": "Completed",
  "未能載入申請。": "Could not load requests.",
  "未能載入申請詳情。": "Could not load request details.",
  "未能更新狀態。": "Could not update status.",
  "未能下載檔案。": "Could not download file.",
  "學校客製化申請": "School Customization Requests",
  "新": "New",
  "查看教師提交的角色需求、教材及跟進狀態。": "Review teachers' character requirements, materials, and follow-up status.",
  "重新整理": "Refresh",
  "全部": "All",
  "暫時沒有申請": "No Requests Yet",
  "新提交的申請將顯示於此。": "New submissions will appear here.",
  "個角色": "characters",
  "請選擇一份申請": "Select a Request",
  "提交時間": "Submitted At",
  "角色需求 ·": "Character Requirements ·",
  "教材文字": "Teaching Material Text",
  "角色參考圖": "Character Reference Image",
  "教材": "Teaching Materials",
  "此申請已標記為完成": "This request is marked as completed",
  "天空藍": "Sky Blue",
  "乾淨、明亮、偏產品感": "Clean, bright, and modern",
  "米紙白": "Rice Paper",
  "柔和、通用、閱讀友好": "Soft, versatile, and easy to read",
  "森林綠": "Forest Green",
  "穩定、自然、偏教育感": "Calm, natural, and educational",
  "暖日落": "Warm Sunset",
  "更有溫度、偏品牌感": "Warm and distinctive",
  "霧灰": "Mist Gray",
  "低調、專業、偏工作台": "Understated and professional",
  "暖色": "Warm",
  "深夜": "Midnight",
  "柔和卡片": "Soft Cards",
  "玻璃感": "Glass",
  "載入帳戶失敗": "Could not load accounts",
  "頭像已更新，記得按儲存": "Avatar updated. Remember to save.",
  "新密碼與確認密碼不一致": "The new password and confirmation do not match",
  "設定更新失敗": "Could not update settings",
  "設定已更新": "Settings updated",
  "重置失敗": "Could not reset",
  "已重置該帳戶的使用次數": "Account usage has been reset",
  "更新失敗": "Could not update",
  "更新上限失敗": "Could not update limit",
  "請填寫完整的新帳戶資料": "Complete all new account details",
  "新帳戶密碼至少需要 8 個字元": "The new account password must contain at least 8 characters",
  "建立帳戶失敗": "Could not create account",
  "已建立新帳戶": "New account created",
  "載入 Bot 清單失敗": "Could not load bots",
  "請先選擇 Bot 與目標帳戶": "Select a bot and destination account first",
  "Bot 歸屬轉移失敗": "Could not transfer bot ownership",
  "Bot 歸屬已更新": "Bot ownership updated",
  "不能刪除目前登入中的管理員帳戶": "You cannot delete the administrator account you are signed in with",
  "刪除帳戶": "Delete Account",
  "確定要刪除此帳戶嗎？此操作無法撤銷。": "Delete this account? This action cannot be undone.",
  "確認刪除": "Confirm Deletion",
  "取消": "Cancel",
  "刪除帳戶失敗": "Could not delete account",
  "帳戶已刪除": "Account deleted",
  "帳戶與系統設定": "Account and System Settings",
  "管理帳戶資料、個人偏好與平台設定。": "Manage your account, personal preferences, and platform settings.",
  "個人帳戶": "Personal Account",
  "介面與偏好": "Interface and Preferences",
  "平台管理": "Platform Administration",
  "目前角色": "Current Role",
  "帳戶權限": "Account Permissions",
  "使用方案": "Current Plan",
  "目前訂閱方案": "Current Subscription",
  "帳戶總數": "Total Accounts",
  "平台已建立帳戶": "Accounts Created",
  "Bot 數量": "Bot Count",
  "可管理的 AI Bot": "Manageable AI Bots",
  "僅管理員可查看": "Administrators Only",
  "個人資料": "Profile",
  "這些是其他網站最常見的帳戶基本資料設定。": "Manage your basic account details.",
  "更換頭像": "Change Avatar",
  "修改電郵時需要輸入目前密碼確認。": "Enter your current password to confirm an email change.",
  "管理密碼與電郵驗證，保護帳戶登入安全。": "Manage your password and email verification to protect your account.",
  "新密碼": "New Password",
  "調整整個工作台的主背景與視覺風格。": "Adjust the workspace background and visual style.",
  "主題模式": "Theme",
  "背景風格": "Background Style",
  "卡片樣式": "Card Style",
  "使用偏好": "Preferences",
  "這些選項在大多數平台都屬於常見個人化設定。": "Personalize your platform experience.",
  "產品更新通知": "Product Updates",
  "接收新功能與更新電郵": "Receive emails about new features and updates",
  "每週摘要": "Weekly Summary",
  "每週收到功能使用與更新摘要": "Receive a weekly usage and update summary",
  "安全通知": "Security Notifications",
  "登入與帳戶異常變更提醒": "Alerts for sign-ins and unusual account changes",
  "自動播放語音": "Autoplay Voice",
  "聊天語音生成後自動播放": "Automatically play generated chat audio",
  "Enter 直接送出": "Enter to Send",
  "關閉後改成 Enter 換行、按鈕送出": "When off, Enter adds a new line; use the button to send",
  "減少動畫": "Reduce Motion",
  "降低界面過場與動態效果": "Reduce interface transitions and animations",
  "語言": "Language",
  "繁體中文（香港）": "Traditional Chinese (Hong Kong)",
  "简体中文": "Simplified Chinese",
  "儲存所有設定": "Save All Settings",
  "使用者帳號": "User Accounts",
  "管理平台成員、方案及功能用量。": "Manage members, plans, and feature usage.",
  "刷新中": "Refreshing…",
  "刷新": "Refresh",
  "邀請成員": "Invite Members",
  "建立新帳戶": "Create New Account",
  "姓名": "Name",
  "初始密碼（至少8位）": "Initial password (at least 8 characters)",
  "教師": "Teacher",
  "建立中...": "Creating…",
  "建立帳戶": "Create Account",
  "搜尋姓名或電子郵件": "Search by name or email",
  "每頁": "Per page",
  "位": "people",
  "成員": "Member",
  "方案": "Plan",
  "本月用量": "Monthly Usage",
  "操作": "Actions",
  "未命名帳戶": "Unnamed Account",
  "不限用量": "Unlimited Usage",
  "無限制": "Unlimited",
  "已選取": "Selected",
  "詳情": "Details",
  "找不到符合條件的帳戶。": "No matching accounts found.",
  "顯示": "Showing",
  "，共": ", total",
  "個帳戶": "accounts",
  "上一頁": "Previous",
  "下一頁": "Next",
  "重置用量": "Reset Usage",
  "刪除中": "Deleting…",
  "儲存修改": "Save Changes",
  "Bot 歸屬整理": "Bot Ownership",
  "把現有 Bot 轉移至正確帳戶。": "Transfer existing bots to the correct accounts.",
  "刷新 Bot": "Refresh Bots",
  "未命名 Bot": "Untitled Bot",
  "未分配帳戶": "Unassigned Account",
  "選擇目標帳戶": "Select Destination Account",
  "轉移中...": "Transferring…",
  "轉移歸屬": "Transfer Ownership",
  "目前歸屬：": "Current Owner:",
  "未知": "Unknown",
  "正在載入聊天...": "Loading chat…",
  "無法打開此聊天：": "Cannot open this chat:",
  "機器人不存在": "Bot not found",
  "聊天視窗已關閉": "Chat Closed",
  "重新整理頁面即可再次打開這個分享聊天。": "Refresh the page to reopen this shared chat.",
  "記憶 (Remember)": "Remember",
  "提取事實與概念": "Recall facts and concepts",
  "理解 (Understand)": "Understand",
  "解釋想法與邏輯": "Explain ideas and reasoning",
  "應用 (Apply)": "Apply",
  "運用於新情境": "Apply knowledge in new situations",
  "分析 (Analyze)": "Analyze",
  "拆解資訊的關聯": "Examine connections in information",
  "評價 (Evaluate)": "Evaluate",
  "批判與辯護": "Critique and justify",
  "創造 (Create)": "Create",
  "產出原創作品": "Produce original work",
  "初次啟航": "First Voyage",
  "與 AI 夥伴完成第一次對話，學習之旅正式啟程": "Complete your first conversation with an AI buddy to begin your learning journey",
  "首次與 AI 夥伴對話": "First conversation with an AI buddy",
  "連勝新手": "Streak Beginner",
  "連續 5 天與夥伴對話，好習慣正在養成": "Chat with a buddy for 5 consecutive days to build a learning habit",
  "連續 5 天與夥伴對話": "Chat with a buddy for 5 consecutive days",
  "早起之鳥": "Early Bird",
  "早上 6–10 點就開始學習，比太陽還勤奮": "Start learning between 6 and 10 a.m.—up with the sun",
  "早上 6:00–10:00 學習": "Learn between 6:00 and 10:00 a.m.",
  "連勝高手": "Streak Expert",
  "連續 10 天不間斷，堅持就是你的超能力": "Keep going for 10 consecutive days—persistence is your superpower",
  "連續 10 天與夥伴對話": "Chat with a buddy for 10 consecutive days",
  "STEM 大師": "STEM Master",
  "STEM 測驗拿下 85 分以上，數理科技小天才": "Score at least 85 on a STEM quiz",
  "STEM 測驗得分 ≥85": "STEM quiz score ≥85",
  "文字魔法師": "Word Wizard",
  "與寫作夥伴對話 10 次以上，筆下生花": "Chat with writing buddies at least 10 times and let your creativity bloom",
  "與寫作/語文夥伴對話 ≥10 次": "Chat with writing/language buddies ≥10 times",
  "好奇寶寶": "Curious Explorer",
  "累計發出 100 則訊息，十萬個為什麼": "Send 100 messages and keep asking why",
  "累計對話訊息 ≥100 則": "Total conversation messages ≥100",
  "語法大師": "Grammar Master",
  "英文文法測驗連續 5 次滿分": "Get full marks on 5 consecutive English grammar quizzes",
  "知識探險家": "Knowledge Explorer",
  "跨越學科邊界，探索知識大陸": "Cross subject boundaries and explore new knowledge",
  "與 ≥4 個不同學科的夥伴對話": "Chat with buddies from ≥4 different subjects",
  "閃電俠": "Lightning Fast",
  "10 分鐘內連續完成 5 次對話，快如閃電": "Complete 5 conversations within 10 minutes",
  "10 分鐘內完成 5 次對話": "Complete 5 conversations within 10 minutes",
  "完美主義者": "Perfectionist",
  "連續 3 次測驗全對，分毫不差": "Answer every question correctly in 3 consecutive quizzes",
  "連續 3 次測驗全對": "Get full marks on 3 consecutive quizzes",
  "全能學者": "All-round Scholar",
  "各學科知識點覆蓋率達 80% 以上": "Reach at least 80% knowledge coverage in every subject",
  "各學科知識點覆蓋 ≥80%": "Knowledge coverage ≥80% in every subject",
  "神祕徽章": "Mystery Badge",
  "已對話機器人": "Bots Chatted With",
  "已聊知識點": "Concepts Discussed",
  "今日互動": "Interactions Today",
  "累計訊息": "Total Messages",
  "🔥 連勝之路": "🔥 Learning Streak",
  "天": "days",
  "🎉 恭喜！你已達成 10 天最高里程碑！": "🎉 Congratulations! You reached the 10-day milestone!",
  "載入失敗": "Could not load",
  "載入學習維度失敗": "Could not load learning dimensions",
  "🏆 我的成就": "🏆 My Achievements",
  "記錄你的成長軌跡，見證每一個進步": "Track your growth and celebrate every step forward",
  "我的學習維度": "My Learning Dimensions",
  "學習維度暫時無法載入：": "Learning dimensions are temporarily unavailable:",
  "🏅 勳章收藏": "🏅 Badge Collection",
  "已解鎖": "Unlocked",
  "收起": "Collapse",
  "展開全部": "Expand All",
  "測試題": "Quiz",
  "未分類": "Uncategorized",
  "次": "times",
  "選擇一位學習夥伴": "Choose a Study Buddy",
  "學習夥伴說明": "Study Buddy Information",
  "正在載入老師分享的 AI Bot...": "Loading AI buddies shared by your teacher…",
  "選擇一位學習夥伴，開始今天的冒險": "Pick a buddy and start today's adventure",
  "老師尚未分享 AI Bot 給你": "Your teacher has not shared any AI buddies with you yet",
  "學習夥伴": "Study Buddies",
  "今日任務": "Today's Tasks",
  "我的成就": "My Achievements",
  "如何選擇學習夥伴": "How to Choose a Study Buddy",
  "點擊任一張卡片即可開始與這位 AI 夥伴聊天。頭像會依老師設定呈現，讓你先感受它的個性再開始對話。": "Select a card to chat with that AI buddy. Its avatar is set by your teacher so you can get a feel for its personality.",
  "同學": "Student",
  "中": "ZH",
  "昨天": "Yesterday",
  "正在開啟…": "Opening…",
  "載入今日任務失敗": "Could not load today's tasks",
  "更新任務狀態失敗": "Could not update task status",
  "開啟任務失敗": "Could not open task",
  "📋 今日任務": "📋 Today's Tasks",
  "老師給你的新消息與待完成挑戰": "New messages and challenges from your teachers",
  "重新載入": "Reload",
  "正在載入真實任務…": "Loading your tasks…",
  "暫時沒有新任務": "No New Tasks Yet",
  "老師新分享的 Bot 或測驗會顯示在這裡": "Bots and quizzes shared by your teachers will appear here",
  "回星際地圖": "Back to Star Map",
  "待完成": "To Do",
  "知識測試": "Knowledge Quiz",
  "去做測試": "Take Quiz",
  "查看 Bot": "View Bot",
  "老師分享（最近 3 天）": "Teacher Shares (Last 3 Days)",
  "分享了機器人「": "shared the bot “",
  "」給你": "” with you",
  "開始對話": "Start Chat",
  "載入學生失敗": "Could not load students",
  "載入分享資料失敗": "Could not load sharing details",
  "加入學生失敗": "Could not add student",
  "保存分享設定失敗": "Could not save sharing settings",
  "分享設定已保存": "Sharing settings saved",
  "先加入學生帳戶，再選擇要分享給每位學生的 AI Bot。": "Add student accounts, then choose which AI bots to share with each student.",
  "我的學生": "My Students",
  "輸入學生帳戶電郵": "Enter the student's account email",
  "加入學生": "Add Student",
  "尚未加入學生。": "No students added yet.",
  "選擇 Bot 與學生": "Select Bots and Students",
  "先選 Bot，再在右側快速配置可共享的學生名單。": "Select a bot, then choose the students who can access it.",
  "位學生": "students",
  "· 已選": "· Selected",
  "點選學生卡片切換": "Select student cards to toggle access",
  "搜尋學生姓名或電郵": "Search by student name or email",
  "清除": "Clear",
  "學生名單": "Student List",
  "已選學生數：": "Students Selected:",
  "保存中...": "Saving…",
  "保存分享設定": "Save Sharing Settings",
  "尚未選擇 Bot。": "No bot selected.",
  "身心安全": "Wellbeing",
  "🚨 關懷提示": "🚨 Wellbeing Alert",
  "系統留意到作答中包含較為負面或不安的情緒描寫，建議進一步關注學生的身心狀況。": "The response contains negative or distressed emotions. Consider checking on the student's wellbeing.",
  "最近覺得壓力很大，活著好像沒什麼意義，根本不想寫作業...": "I have been feeling very stressed. Life feels meaningless, and I do not want to do homework…",
  "非原創/AI": "Non-original / AI",
  "⚠️ 學術提示": "⚠️ Academic Integrity Alert",
  "此份作答的語言特徵異常，可能包含非原創或 AI 生成內容，建議核實。": "Unusual language patterns may indicate non-original or AI-generated content. Please review.",
  "不當言論": "Inappropriate Language",
  "⚠️ 內容提示": "⚠️ Content Alert",
  "作答中疑似包含攻擊性或不適宜的詞彙，請檢視內容並酌情引導。": "The response may contain offensive or inappropriate language. Review it and provide guidance as needed.",
  "這題目真的有夠蠢，不想寫，出題的老師腦袋有洞吧。": "This question is really stupid. I do not want to do it. What was the teacher thinking?",
  "私隱洩漏": "Privacy Disclosure",
  "🛡️ 私隱提示": "🛡️ Privacy Alert",
  "作答中疑似包含敏感的個人或家庭私隱資訊，請妥善保護數據。": "The response may include sensitive personal or family information. Please protect this data.",
  "我爸爸最近失業了，我們家住在九龍旺角彌敦道123號5樓，電話是98765432，所以很煩惱。": "My dad recently lost his job. We live at 123 Nathan Road, Mong Kok, fifth floor, and our phone number is 98765432. I am worried.",
  "敷衍/偏題": "Off-topic / Low Effort",
  "💡 狀態提示": "💡 Engagement Alert",
  "作答內容與題目嚴重偏離或出現無意義字元，可能反映學生遇到學習困難。": "The response is substantially off-topic or contains meaningless characters, which may indicate learning difficulties.",
  "asdfasdfasdf 不知道 不知道 不知道": "asdfasdfasdf I do not know I do not know I do not know",
  "你認為桃花源是一個理想的社會嗎？請結合文本説明你的觀點。": "Do you think the Peach Blossom Spring is an ideal society? Support your view with evidence from the text.",
  "學生作答": "Student Response",
  "AI 預批": "AI Preliminary Grade",
  "草擬評語": "Draft Feedback",
  "作答內容未能針對題目進行有效論述，請老師進一步瞭解學生的學習狀況或給予適當引導。": "The response does not address the question effectively. Please check the student's learning needs and provide guidance.",
  "/ 5 分": "/ 5 points",
  "判斷依據": "Rationale",
  "根據系統偵測，此作答觸發了「": "This response triggered the “",
  "」的異常警示，因此暫不給予常規評分，建議由教師人工介入處理。": "” alert. Standard grading is paused; teacher review is recommended.",
  "確認": "Confirm",
  "修改": "Edit",
  "重新生成": "Regenerate",
  "參考答案：": "Reference Answer:",
  "刪除題庫失敗，請稍後再試。": "Could not delete question bank. Please try again later.",
  "返回指揮艙": "Back to Command Center",
  "搜尋題庫名稱...": "Search question banks…",
  "最近更新": "Recently Updated",
  "共": "Total",
  "查看完整題目": "View Full Questions",
  "還沒有題庫，先從測驗預覽把題目加入題庫吧。": "No question banks yet. Add questions from the quiz preview to get started.",
  "下載 PDF": "Download PDF",
  "分享題庫": "Share Question Bank",
  "刪除題庫": "Delete Question Bank",
  "此題庫暫無題目": "No questions in this bank yet",
  "評測質量總覽": "Assessment Quality Overview",
  "平均": "Average",
  "分": "points",
  "- 質量分析": "- Quality Analysis",
  "發佈日期:": "Published:",
  "本次測驗平均分": "Average Quiz Score",
  "AI 與教師分數差異": "AI vs. Teacher Score Difference",
  "教師修改率": "Teacher Adjustment Rate",
  "異常作答標記": "Flagged Responses",
  "📝 題目得分明細": "📝 Question Score Details",
  "匯出 CSV": "Export CSV",
  "題目 ID": "Question ID",
  "題型": "Question Type",
  "布魯姆層級": "Bloom's Level",
  "AI 分數": "AI Score",
  "教師最終分數": "Final Teacher Score",
  "差值": "Difference",
  "正在載入草稿內容...": "Loading draft…",
  "此份作答語言特徵異常，建議老師進一步核實是否存在非原創內容。": "Unusual language patterns detected. Please review whether the response contains non-original content.",
  "作答中疑似包含攻擊性或不適宜詞彙，建議老師查看。": "The response may contain offensive or inappropriate language. Teacher review is recommended.",
  "作答中可能出現敏感個資，建議老師妥善處理。": "The response may contain sensitive personal information. Please handle it carefully.",
  "作答內容偏短或偏離題意，學生可能尚未真正投入作答。": "The response is short or off-topic. The student may not be fully engaged yet.",
  "開放式答案": "Open-ended Answer",
  "測驗詳情": "Quiz Details",
  "正在載入學生作答...": "Loading student responses…",
  "待確認": "Awaiting Confirmation",
  "待批改": "Awaiting Grading",
  "批改進度": "Grading Progress",
  "人": "people",
  "提交於": "Submitted",
  "總分": "Total Score",
  "學生作答：": "Student Response:",
  "未作答": "Not Answered",
  "正確答案：": "Correct Answer:",
  "AI 評語：": "AI Feedback:",
  "本次平均分": "Average Score",
  "· 異常標記": "· Alerts",
  "儲存草稿": "Save Draft",
  "發佈中...": "Publishing…",
  "批量發佈成績": "Publish All Grades",
  "刪除測驗失敗": "Could not delete quiz",
  "刪除失敗": "Could not delete",
  "測驗暫時無法刪除，請稍後再試。": "This quiz cannot be deleted right now. Please try again later.",
  "刪除測驗？": "Delete Quiz?",
  "刪除": "Delete",
  "AI 批改説明": "About AI Grading",
  "份測驗待處理 · 共": "quizzes to process · Total",
  "份學生作答": "student responses",
  "正在載入批改資料...": "Loading grading data…",
  "還沒有測驗，兩步驟就能開始批改": "No quizzes yet. Start grading in two steps.",
  "完成後，學生作答會自動出現在這裡讓你確認分數": "Student responses will appear here for you to confirm their scores",
  "到「機器人角色」幫角色加上題目": "Add questions to a bot character",
  "上傳課文或題目，AI 會自動整理成測驗，不用自己一題一題輸入。": "Upload a lesson or questions, and AI will organize them into a quiz.",
  "發布給班級，等學生作答": "Publish to your class and wait for responses",
  "學生答完後會自動送到這裡，AI 先批改一次，你只需要確認或調整分數即可。": "Responses are sent here automatically. AI grades them first; you confirm or adjust the scores.",
  "前往機器人角色設定題目": "Set Up Bot Questions",
  "查看報告": "View Report",
  "去確認": "Review",
  "開始批改": "Start Grading",
  "AI 批改怎麼運作": "How AI Grading Works",
  "學生作答後，AI 會先自動評分並給出建議分數，例如選擇題直接判對錯、簡答題會給參考理由。你可以直接採用，也能手動調整後再確認送出。": "AI suggests scores after students respond: multiple-choice answers are checked automatically, and short answers include a rationale. Accept or adjust scores before confirming.",
  "批准": "Approve",
  "修改評語": "Edit Feedback",
  "AI 原始草稿": "Original AI Draft",
  "請輸入評語...": "Enter feedback…",
  "得分：": "Score:",
  "完成並儲存": "Finish and Save",
  "今日": "Today",
  "昨日": "Yesterday",
  "過去 7 天": "Last 7 Days",
  "更早": "Earlier",
  "對話紀錄": "Conversation History",
  "完成": "Done",
  "管理": "Manage",
  "重新整理對話紀錄": "Refresh Conversation History",
  "關閉對話紀錄": "Close Conversation History",
  "取消全選": "Deselect All",
  "全選": "Select All",
  "已選": "Selected",
  "項": "items",
  "管理功能正在更新，請重新開啟對話紀錄": "Management tools are updating. Reopen conversation history.",
  "新增對話": "New Conversation",
  "搜尋對話": "Search conversations",
  "正在載入對話...": "Loading conversations…",
  "目前沒有聊天紀錄": "No conversation history yet",
  "尚未開始對話": "No conversation started yet",
  "重新命名": "Rename",
  "記憶": "Remember",
  "理解": "Understand",
  "應用": "Apply",
  "分析": "Analyze",
  "評價": "Evaluate",
  "創造": "Create",
  "喚醒 AI 助教：為您深入分析「評價」與「創造」層級的教學策略...": "AI assistant: analyzing teaching strategies for the Evaluate and Create levels…",
  "能力追蹤報告": "Ability Tracking Report",
  "過去 7 日": "Last 7 Days",
  "過去一個月": "Last Month",
  "一鍵生成詳細報告": "Generate Detailed Report",
  "班級視圖": "Class View",
  "學生視圖": "Student View",
  "- 能力輪廓": "- Ability Profile",
  "近期表現": "Recent Performance",
  "過往平均": "Previous Average",
  "AI 洞察": "AI Insights",
  "全班在「評價」與「創造」層級得分率均低於 40%，建議近期課堂增加開放討論環節。": "The class scored below 40% in Evaluate and Create. Consider adding open discussions to upcoming lessons.",
  "已掌握": "Mastered",
  "接近掌握": "Nearly Mastered",
  "進行中": "In Progress",
  "需要加強": "Needs Improvement",
  "目前尚未提供角色知識庫摘要。": "No character knowledge-base summary is available yet.",
  "待加強": "Needs Improvement",
  "L1 基礎事實": "L1 Basic Facts",
  "可直接回憶基本資料": "Recall basic information directly",
  "請在角色知識庫中補充知識點分級": "Add knowledge levels to the character's knowledge base",
  "目前尚未偵測到可用的基礎事實知識點": "No basic-fact knowledge points detected yet",
  "L2 理解關聯": "L2 Understanding Connections",
  "能把事實串成因果": "Connect facts through cause and effect",
  "目前尚未偵測到可用的理解關聯知識點": "No relational-understanding knowledge points detected yet",
  "L3 深度遷移": "L3 Deep Transfer",
  "已能跨段落建立關聯": "Connect ideas across passages",
  "目前尚未偵測到可用的深度遷移知識點": "No deep-transfer knowledge points detected yet",
  "共享 Bot": "Shared Bot",
  "本堂課目前尚未開始互動，班級還沒有累積足夠的輸入記錄，等學生開始回應後，這裡會依實際佔比自動更新。": "No interactions yet this lesson. This analysis will update automatically when students start responding.",
  "本堂課整體互動偏向主動輸入。學生以直接回應為主，表示當前知識點能促使學生自行輸出，可適度提高挑戰度。": "Students mostly respond independently this lesson. The current concepts encourage active output; consider increasing the challenge.",
  "本堂課整體互動偏向系統引導。學生較常依賴提示或引導回覆，表示當前知識點仍需要更多支架支持，建議先降低門檻，再逐步提高挑戰度。": "Students mostly rely on guidance this lesson. Provide more support, start with accessible tasks, and gradually increase the challenge.",
  "本堂課整體互動剛好平衡。學生直接回應與系統引導各佔一半，表示當前知識點能同時支撐自主輸出與適度提示，適合維持目前難度並觀察後續走向。": "Independent and guided responses are balanced this lesson. Maintain the current difficulty and monitor progress.",
  "知識點": "Knowledge Point",
  "尚無時間": "No Timestamp",
  "查看由實際對話累積的學習分析": "View learning analysis based on actual conversations",
  "正在同步能力追蹤資料…": "Syncing ability tracking data…",
  "暫時無法載入能力追蹤資料，請稍後再試。": "Could not load ability tracking data. Please try again later.",
  "尚未分享 AI 夥伴給學生；分享後會在此累積真實互動資料。": "No AI buddies have been shared with students yet. Actual interaction data will appear after sharing.",
  "返回": "Back",
  "班級思維自主指數": "Class Independent Thinking Index",
  "主動輸入 (Independent):": "Independent Input:",
  "系統引導 (Assisted):": "System Guidance:",
  "學生排行榜": "Student Leaderboard",
  "班級知識覆蓋地圖": "Class Knowledge Coverage Map",
  "展示全班各知識點的集體解鎖進度": "Collective progress in unlocking each knowledge point",
  "學習狀態分佈矩陣": "Learning Status Matrix",
  "總掌握度 (0-100%)": "Overall Mastery (0–100%)",
  "高效學握區": "Efficient Mastery",
  "基礎/淺層參與區": "Basic / Surface Participation",
  "無效卡關": "Stuck",
  "低輪次": "Fewer Turns",
  "互動輪次": "Interaction Turns",
  "高輪次": "More Turns",
  "查看全班評估明細": "View Class Assessment Details",
  "學生與": "Students and",
  "對話記錄": "Conversation Records",
  "查看": "View",
  "位學生與「": "students chatting with “",
  "目前 Bot": "Current Bot",
  "」的學習對話": "”",
  "搜尋學生或對話內容": "Search students or conversations",
  "則訊息 ·": "messages ·",
  "尚無對話": "No Conversations",
  "找不到符合的對話記錄": "No matching conversations found",
  "則": "messages",
  "目前沒有可顯示的對話": "No conversations to display",
  "學生開始與這個 Bot 互動後，記錄會出現在這裡。": "Records will appear when students start interacting with this bot.",
  "互動模式深度分析": "Interaction Pattern Analysis",
  "AI 模式洞察": "AI Pattern Insights",
  "主動輸入/引導依賴佔比": "Independent vs. Guided Input",
  "主動輸入": "Independent Input",
  "系統引導": "System Guidance",
  "平均自由輸入長度": "Average Free-text Length",
  "字": "characters",
  "平均氣泡依賴次數": "Average Suggested-reply Usage",
  "次/人": "times / student",
  "主動輸入/引導依賴佔比排行榜": "Independent vs. Guided Input Leaderboard",
  "主動優先": "Independent First",
  "被動優先": "Guided First",
  "輸入": "Input",
  "依賴": "Reliance",
  "全班評估明細表": "Class Assessment Details",
  "深度檢視學生的知識點交互狀態與品質": "Explore the state and quality of student interactions with knowledge points",
  "輸出品質評級説明": "Output Quality Levels",
  "依學生與 Bot 的聊天內容和角色知識庫匹配結果評估。": "Based on student conversations matched against the character's knowledge base.",
  "L0: 偏離主題": "L0: Off-topic",
  "L1: 基礎事實": "L1: Basic Facts",
  "L2: 事實關聯": "L2: Connections Between Facts",
  "L3: 深度理解": "L3: Deep Understanding",
  "互動深度説明": "Interaction Depth",
  "反映學生在本次學習中主動探索與持續參與的程度。": "Reflects the student's active exploration and sustained participation in this session.",
  "Y1: 初步參與": "Y1: Initial Participation",
  "Y2: 持續互動": "Y2: Sustained Interaction",
  "Y3: 深入探索": "Y3: Deep Exploration",
  "Y4: 高度投入": "Y4: Highly Engaged",
  "資料暫時無法載入，目前不顯示推測或示例數值。": "Data is unavailable. Estimated or sample values are not shown.",
  "正在同步學生聊天與知識庫分析...": "Syncing student conversations and knowledge-base analysis…",
  "總掌握度": "Overall Mastery",
  "輸出品質": "Output Quality",
  "互動深度": "Interaction Depth",
  "參與模式": "Participation Mode",
  "狀態": "Status",
  "掌握": "Mastery",
  "輪": "turns",
  "尚未累積足夠的學生互動資料；學生開始對話後，能力追蹤會自動更新。": "Not enough student interaction data yet. Ability tracking updates automatically when conversations begin.",
  "— 知識掌握追蹤": "— Knowledge Mastery Tracking",
  "整體狀態": "Overall Status",
  "掌握度": "Mastery",
  "互動": "Interactions",
  "輪對話": "conversation turns",
  "知識掌握分層": "Knowledge Mastery Levels",
  "依據目前角色「": "Automatically organized from the knowledge base of “",
  "」的知識庫內容自動整理。": "”.",
  "方案用量": "Plan Usage",
  "切換語言": "Switch Language",
  "清除搜尋": "Clear Search",
  "指揮倉": "Command Center",
  "AI工作坊": "AI Workshop",
  "學生與分享": "Students and Sharing",
  "客製化申請": "Customization Request",
  "設定": "Settings",
  "繁體中文 / EN": "Chinese / EN",
  "登入 / 註冊": "Sign In / Register",
  "幫助": "Help",
  "登出": "Sign Out",
  "未登入": "Not Signed In",
  "請先登入帳戶": "Please sign in first",
  "文本與年級": "Text and Grade",
  "預覽與儲存": "Preview and Save",
  "預覽與發佈": "Preview and Publish",
  "星際地圖": "Star Map",
  "創意實驗室": "Creative Lab",
  "成就博物館": "Achievement Museum",
  "Lv. 5 冒險家": "Lv. 5 Adventurer",
  "3 天連勝": "3-day Streak",
  "3月1日": "March 1",
  "簡單": "Easy",
  "中等": "Medium",
  "困難": "Hard",
  "學習路徑：初級冒險家": "Learning Path: Beginner Adventurer",
  "每日登錄獎勵": "Daily Sign-in Reward",
  "過去一小時": "Last Hour",
  "過去一日": "Last Day",
  "過去七日": "Last 7 Days",
  "Token 消耗記錄": "Token Usage History",
  "剩餘可用：": "Available:",
  "關閉": "Close",
  "該時段沒有記錄": "No records in this period",
  "測試版 / Demo 版": "Beta / Demo",
  "目前為功能測試階段，內容與體驗可能隨時調整，感謝你的試用與回饋。": "Features are being tested and may change. Thank you for trying the platform and sharing feedback.",
  "關閉提示": "Dismiss Notice",
  "創建角色": "Create Character",
  "目前已建立的 AI 角色數量": "Number of AI characters currently created",
  "對話次數": "Conversations",
  "學生與 AI 角色的對話訊息數": "Messages between students and AI characters",
  "此帳戶無限制": "This Account Is Unlimited",
  "已用": "Used",
  "感謝試用": "Thanks for Trying the Platform",
  "感謝您試用我們的機器人平台！": "Thank you for trying our bot platform!",
  "我們的開發團隊十分想聽到您的意見。如果你想提供意見，或瞭解和購買我們的機器人創建服務，歡迎直接聯絡我們。": "Our development team would love your feedback. Contact us to share your thoughts or learn about our bot creation service.",
  "歡迎提交產品意見、合作需求或購買方案查詢。": "Contact us with product feedback, collaboration ideas, or plan inquiries.",
  "瞭解": "Learn More",
  "知道了": "Got It",
  "正常": "Normal",
  "需配置": "Setup Required",
  "接口異常": "API Error",
  "不支援": "Unsupported",
  "第三方 API 額度監控": "Third-party API Quotas",
  "正在更新配額資料...": "Updating quota data…",
  "剩餘：未知": "Remaining: Unknown",
  "更新：": "Updated:",
  "尚無可用資料": "No Data Available",
  "錯誤：": "Error:",
  "科目標籤説明": "About Subject Labels",
  "編輯 →": "Edit →",
  "（未收到回覆）": "(No response received)",
  "發送失敗，請稍後再試。": "Could not send. Please try again later.",
  "最多隻能上傳四張圖片": "You can upload up to four images",
  "角色構建中…": "Building Character…",
  "輸入訊息測試...": "Enter a test message…",
  "基礎設定": "Basic Settings",
  "形象與人格": "Appearance and Personality",
  "聲音與動畫": "Voice and Animation",
  "知識餵養": "Knowledge Base",
  "安全與權限": "Safety and Permissions",
  "我的 AI 機器人": "My AI Bot",
  "點頭回應": "Nodding Response",
  "無法載入角色資料": "Could not load character details",
  "正在載入角色資料…": "Loading character details…",
  "無法開啟角色編輯頁": "Could not open the character editor",
  "返回機器人庫": "Back to Bot Library",
  "返回我的機器人庫": "Back to My Bot Library",
  "知識與教學設定": "Knowledge and Teaching Settings",
  "先設定所有對話共用的角色基礎，再整理知識內容與各主題的專屬教學資料。": "Set the character's shared foundations, then organize knowledge and topic-specific teaching materials.",
  "上一步": "Previous Step",
  "下一步": "Next Step",
  "完成並發布": "Finish and Publish",
  "更新機器人": "Update Bot",
  "發布中...": "Publishing…",
  "發布失敗，請稍後再試。": "Could not publish. Please try again later.",
  "請先輸入機器人名稱。": "Enter a bot name first.",
  "請先完成頭像與背景設定。": "Complete the avatar and background settings first.",
  "動畫正在背景生成中，你可以先繼續下一步。": "Animations are generating in the background. You can continue to the next step.",
  "請先完成音色與三段動畫影片。": "Complete the voice and all three animation videos first.",
  "請先完成知識餵養內容整理。": "Complete the knowledge-base content first.",
  "請先選擇學科分類。": "Select a subject first.",
  "請先完成安全與權限設定。": "Complete the safety and permissions settings first.",
  "影片生成完成": "Videos Generated",
  "三段動畫已全部完成，現在可以發布了。": "All three animations are ready. You can publish now.",
  "三段動畫仍在背景生成中，完成後才可發布。": "The three animations are still generating in the background. Publish once they are ready.",
  "人物背景": "Character Background",
  "説話風格": "Speaking Style",
  "生活興趣": "Interests",
  "對話示例": "Example Conversations",
  "知識主題": "Knowledge Topic",
  "深度理解": "Deep Understanding",
  "文言文": "Classical Chinese",
  "引導後再回答": "Guide Before Answering",
  "耐心": "Patient",
  "免費版的機器人數量上限": "Free Plan Bot Limit",
  "免費方案可建立的機器人角色數量有限。升級付費方案可取得更多角色席位及更高的對話用量。": "The free plan has a limited number of character slots. Upgrade for more slots and a higher conversation allowance.",
  "PRO 方案的對話訊息不限量，機器人角色則按席位使用。如需更多席位，可直接聯絡客服協助加開。": "PRO includes unlimited conversation messages with a set number of character slots. Contact support to add slots.",
  "科目標籤顏色": "Subject Label Colors",
  "顏色代表機器人所屬的科目，方便你在多個角色中快速分類。點擊卡片即可重新設定科目與顏色。": "Colors identify each bot's subject. Select a card to change its subject and color.",
  "建立屬於您的 AI 夥伴": "Create Your AI Buddy",
  "從角色外觀、知識庫、對話風格到教學情境，一次打造可立即投入課堂的 AI 機器人。": "Customize appearance, knowledge, conversation style, and teaching scenarios to create a classroom-ready AI bot.",
  "你的方案用量": "Your Plan Usage",
  "免費版功能次數": "Free Feature Allowance",
  "建立機器人角色": "Create Bot Character",
  "機器人角色席位": "Bot Character Slots",
  "對話訊息": "Conversation Messages",
  "PRO 方案不限對話次數": "Unlimited Conversations on PRO",
  "已達機器人上限": "Bot Limit Reached",
  "洽客服可加開更多席位": "Contact support for more slots",
  "創建新機器人": "Create New Bot",
  "開始打造您的下一位 AI 夥伴": "Start building your next AI buddy",
  "還沒有機器人？三步驟就能上線": "No bots yet? Get started in three steps.",
  "完成後即可分享給學生開始互動": "Share with students and start interacting when ready",
  "設定角色外觀與聲音": "Set Appearance and Voice",
  "上傳知識庫內容與安全提示詞": "Upload Knowledge and Safety Instructions",
  "發布並分享連結給學生": "Publish and Share the Link with Students",
  "找不到符合的 AI 機器人": "No Matching AI Bots",
  "暫時無法刪除這個機器人，請稍後再試。": "This bot cannot be deleted right now. Please try again later.",
  "載入中": "Loading",
  "刪除機器人失敗": "Could not delete bot",
  "Tomato Robot AI 夥伴": "Tomato Robot AI Buddy",
  "粵語": "Cantonese",
  "基礎事實": "Basic Facts",
  "深入思考": "Deeper Thinking",
  "價值遷移": "Applying Values",
  "普通話": "Mandarin",
  "AI 機器人": "AI Bot",
  "無法載入主題": "Could not load topics",
  "新的對話": "New Conversation",
  "無法載入聊天紀錄，請稍後再試。": "Could not load conversation history. Please try again later.",
  "已複製共享連結": "Share Link Copied",
  "現在可以直接分享給學生使用了。": "You can now share it with your students.",
  "複製失敗": "Could Not Copy",
  "目前無法自動複製連結，請稍後再試。": "Could not copy the link automatically. Please try again later.",
  "免費語音功能已用完，已自動切換為純文字回覆。": "Free voice allowance used up. Switched to text replies.",
  "當前瀏覽器不支援畫面錄製": "This browser does not support screen recording",
  "錄製失敗，請重新嘗試": "Recording failed. Please try again.",
  "無法開始錄製畫面": "Could not start screen recording",
  "目前無法拍照": "Cannot take a photo right now",
  "無法建立畫布": "Could not create canvas",
  "圖片載入失敗": "Could not load image",
  "角色影片載入失敗": "Could not load character video",
  "角色影片定位失敗": "Could not seek character video",
  "拍照失敗": "Could not take photo",
  "當前環境不支援相機背景": "Camera backgrounds are not supported in this environment",
  "沒有找到可用攝像頭裝置": "No camera found",
  "瀏覽器已封鎖相機權限": "Camera permission is blocked by the browser",
  "相機權限請求逾時，請檢查瀏覽器權限設定": "Camera permission request timed out. Check your browser permissions.",
  "相機串流已取得，但畫面未成功載入": "Camera connected, but the video did not load",
  "相機畫面初始化失敗": "Could not initialize camera video",
  "相機權限被拒絕或裝置不可用": "Camera permission denied or device unavailable",
  "語音回覆需要登入狀態，請重新登入後再試。": "Sign in again to use voice replies.",
  "語音暫時不可用": "Voice Temporarily Unavailable",
  "目前語音服務發生錯誤，系統已先以文字回覆。請稍後再試。": "The voice service encountered an error. A text reply is available. Please try again later.",
  "目前無法完成回覆，請稍後再試。": "Could not complete the reply. Please try again later.",
  "切換主題失敗，請稍後再試。": "Could not switch topic. Please try again later.",
  "切換主題失敗": "Could Not Switch Topic",
  "請輸入新的對話名稱": "Enter a new conversation name",
  "重新命名失敗": "Could Not Rename",
  "請稍後再試。": "Please try again later.",
  "確定要刪除此對話嗎？": "Delete This Conversation?",
  "刪除後，此對話將不會出現在歷史紀錄中。": "This conversation will be removed from your history.",
  "對話已刪除": "Conversation Deleted",
  "此對話已從歷史紀錄中移除。": "This conversation has been removed from your history.",
  "其中包含目前開啟的對話。刪除後，聊天畫面會重置，且這些對話無法復原。": "This includes the open conversation. The chat will reset, and these conversations cannot be restored.",
  "刪除後，這些對話將不會出現在歷史紀錄中，且無法復原。": "These conversations will be removed from history and cannot be restored.",
  "批量刪除失敗": "Could Not Delete Conversations",
  "對話尚未刪除，請稍後再試。": "The conversations were not deleted. Please try again later.",
  "圖片數量已達上限": "Image Limit Reached",
  "最多隻能上傳四張圖片。": "You can upload up to four images.",
  "不支援語音輸入": "Voice Input Not Supported",
  "此瀏覽器暫不支援語音輸入，建議使用 Chrome。": "This browser does not support voice input. Try Chrome.",
  "麥克風不可用": "Microphone Unavailable",
  "目前環境不支援麥克風權限請求。": "This environment does not support microphone permission requests.",
  "麥克風權限被拒絕": "Microphone Permission Denied",
  "請在瀏覽器設定中允許麥克風後再試。": "Allow microphone access in your browser settings and try again.",
  "無法使用麥克風": "Cannot Use Microphone",
  "請檢查系統與瀏覽器權限後再試。": "Check your system and browser permissions, then try again.",
  "語音輸入權限被拒絕": "Voice Input Permission Denied",
  "請允許麥克風後再試。": "Allow microphone access and try again.",
  "未偵測到語音": "No Speech Detected",
  "請再説一次。": "Please speak again.",
  "找不到麥克風": "Microphone Not Found",
  "目前找不到可用的麥克風裝置。": "No microphone is available.",
  "語音輸入啟動失敗": "Could Not Start Voice Input",
  "你拒絕了麥克風權限，請在瀏覽器設定中允許後再試。": "Microphone permission was denied. Allow access in your browser settings and try again.",
  "授權失敗，請檢查手機瀏覽器麥克風與音訊權限。": "Authorization failed. Check microphone and audio permissions in your mobile browser.",
  "載入測驗失敗": "Could not load quiz",
  "開始測驗失敗": "Could not start quiz",
  "測驗無法開始": "Quiz Cannot Start",
  "開始測驗失敗，請稍後再試。": "Could not start quiz. Please try again later.",
  "提交答案失敗": "Could not submit answer",
  "正在載入下一題...": "Loading next question…",
  "答案同步失敗": "Could Not Sync Answer",
  "提交答案失敗，請稍後再試。": "Could not submit answer. Please try again later.",
  "提交失敗": "Submission Failed",
  "填充題": "Fill in the Blank",
  "收起 AR 控制": "Collapse AR Controls",
  "打開 AR 控制": "Open AR Controls",
  "全身": "Full Body",
  "上半身": "Upper Body",
  "隱藏聊天框": "Hide Chat",
  "顯示聊天框": "Show Chat",
  "打開對話紀錄": "Open Conversation History",
  "更多操作": "More Actions",
  "編輯機器人": "Edit Bot",
  "複製共享連結": "Copy Share Link",
  "刪除機器人": "Delete Bot",
  "相機背景": "Camera Background",
  "已連接": "Connected",
  "啟動中": "Starting",
  "未啟用": "Not Enabled",
  "可拖動角色位置，雙指捏合調整大小。": "Drag to move the character; pinch with two fingers to resize.",
  "可拖動角色位置，並用下方工具調整角色大小。": "Drag to move the character and use the tools below to resize.",
  "正在請求相機權限...": "Requesting camera permission…",
  "啟用後會以電腦相機畫面取代目前背景。": "When enabled, your camera feed replaces the current background.",
  "啟動中...": "Starting…",
  "重新連接": "Reconnect",
  "開啟手機相機": "Open Phone Camera",
  "開啟相機": "Open Camera",
  "結束並下載": "Finish and Download",
  "開始錄製": "Start Recording",
  "關閉 AR": "Close AR",
  "重置位置": "Reset Position",
  "縮小": "Zoom Out",
  "放大": "Zoom In",
  "錄製未啟用：": "Recording not enabled:",
  "點擊停止語音輸入": "Stop Voice Input",
  "語音輸入（廣東話）": "Voice Input (Cantonese)",
  "圖片保存中...": "Saving image…",
  "拍攝當前舞台": "Capture Current Stage",
  "停止回覆與語音": "Stop Reply and Audio",
  "已發佈上線": "Published",
  "選擇主題": "Select Topic",
  "選擇對話主題": "Select Conversation Topic",
  "切換後，下一則回覆會使用新提示與知識。": "The next reply will use the new instructions and knowledge.",
  "預設": "Default",
  "此主題尚未加入説明": "No description has been added to this topic",
  "載入主題": "Load Topics",
  "AI 回覆語言": "AI Reply Language",
  "你有一個待完成的知識測試": "You have a knowledge quiz to complete",
  "點擊開展測試 →": "Start Quiz →",
  "做得好": "Well Done",
  "可改進": "Areas for Improvement",
  "我們現在開始測試。準備好了嗎？請回答我接下來的問題！": "Let's start the quiz. Ready? Answer the following questions!",
  "載入題目...": "Loading questions…",
  "準備答題": "Ready to Answer",
  "稍後作答": "Answer Later",
  "請輸入你的答案...": "Enter your answer…",
  "上一題": "Previous Question",
  "計分中...": "Scoring…",
  "完成作答": "Finish Quiz",
  "下一題": "Next Question",
  "測驗已結束。以下是你的結算報告。": "The quiz has ended. Here is your results report.",
  "測驗結果結算": "Quiz Results",
  "等級": "Grade",
  "表現出色": "Excellent",
  "掌握不錯": "Good Understanding",
  "持續前進": "Keep Going",
  "打穩基礎": "Build Your Foundation",
  "再測一次": "Try Again",
  "完成結算": "Finish",
  "引導模式進行中": "Guided Mode Active",
  "退出引導": "Exit Guided Mode",
  "重複這一步": "Repeat This Step",
  "給我示例": "Show an Example",
  "已收到回覆語音，請點一下畫面以恢復播放。": "Reply audio is ready. Tap the screen to resume playback.",
  "上傳圖片": "Upload Image",
  "輸入訊息，或按麥克風説話...": "Enter a message or tap the microphone to speak…",
  "正在載入聊天與語音...": "Loading chat and voice…",
  "開始體驗前需要一次授權": "Permission Needed to Get Started",
  "點一次即可啟用麥克風與語音播放，之後同一會話可自動語音回覆。": "Enable your microphone and audio once to receive automatic voice replies in this session.",
  "授權中...": "Authorizing…",
  "開始體驗並授權": "Start and Allow Access",
  "確認刪除這個聊天？": "Delete This Chat?",
  "刪除後將無法復原，分享連結也會失效。": "This cannot be undone, and the share link will stop working.",
  "準備中": "Preparing",
  "生成失敗": "Generation Failed",
  "三段動畫已完成": "All Three Animations Ready",
  "背景任務失敗": "Background Task Failed",
  "正在移除背景…（Remove BG）": "Removing background…",
  "影片工作室已用完": "Video Studio Allowance Used Up",
  "免費版影片工作室次數已用完，請升級到付費版。": "Your free Video Studio allowance is used up. Please upgrade to a paid plan.",
  "請先上傳生成照片": "Upload a Photo First",
  "請先上傳一張用於影片生成的人物照片。": "Upload a character photo to generate a video.",
  "測試模式已啟動，不扣 token。": "Test mode enabled. No tokens will be deducted.",
  "背景生成已啟動，稍後會持續更新進度。": "Background generation started. Progress will update automatically.",
  "影片生成失敗，請稍後再試。": "Could not generate video. Please try again later.",
  "影片工作室": "Video Studio",
  "生成照片": "Source Photo",
  "生成照片預覽": "Source Photo Preview",
  "尚未設定 Avatar": "No Avatar Set",
  "請先回到第一步設定角色頭像，影片工作室會直接使用那張照片。": "Go back to the first step and set a character avatar. Video Studio uses that photo.",
  "生成三種動畫": "Generate Three Animations",
  "請先在上方上傳一張專門用來生成影片的人物照片。": "Upload a character photo above for video generation.",
  "保存並返回": "Save and Return",
  "先關閉，去做別的步驟": "Close and Continue Other Steps",
  "生成中": "Generating",
  "可先關閉，背景繼續生成": "You can close this; generation continues in the background",
  "正在生成": "Generating",
  "正在去背": "Removing Background",
  "等待中": "Waiting",
  "待命": "Idle",
  "影片準備開始": "Ready to Generate Video",
  "設定左側參數後開始生成": "Set the parameters on the left to begin",
  "效果預覽": "Preview",
  "影片將根據這裡上傳的照片生成，以下為三種動作效果示意。": "Videos are generated from the uploaded photo. The three animation styles are illustrated below.",
  "載入草稿失敗，請稍後再試。": "Could not load draft. Please try again later.",
  "導入草稿失敗，請稍後再試。": "Could not import draft. Please try again later.",
  "文檔上傳失敗，請稍後再試。": "Could not upload document. Please try again later.",
  "💡 AI 將自動限制高階認知層級，並簡化提問詞彙，適合初小學生。": "💡 AI limits advanced cognitive levels and simplifies vocabulary for younger primary students.",
  "💡 AI 將平衡基礎理解與應用題型，適度增加推論性問題。": "💡 AI balances basic understanding and application, with some inference questions.",
  "💡 AI 將增加分析與評鑑題型，鼓勵學生進行批判性思考。": "💡 AI adds analysis and evaluation questions to encourage critical thinking.",
  "💡 AI 將著重於高階認知層級，模擬公開試題型與深度。": "💡 AI focuses on higher-order thinking with public-exam-style questions and depth.",
  "💡 AI 將根據所選年級自動調整題目難度與認知層級。": "💡 AI adjusts question difficulty and cognitive levels to the selected grade.",
  "請先選擇要發布測驗的 AI Bot。": "Select an AI bot to publish the quiz to first.",
  "請先輸入測驗文本。": "Enter the quiz text first.",
  "請先選擇目標年級。": "Select the target grade first.",
  "請選擇有效的題目數量。": "Select a valid number of questions.",
  "AI 題目生成失敗，請稍後再試。": "Could not generate questions. Please try again later.",
  "文本材料": "Text Materials",
  "從草稿導入": "Import from Draft",
  "從歷史題庫導入": "Import from Question Bank History",
  "題庫導入": "Import Question Bank",
  "文檔解析中...": "Parsing document…",
  "上傳文檔": "Upload Document",
  "解析中": "Parsing",
  "上傳": "Upload",
  "請在此貼上文章內容，或點擊右上角上傳文檔 (支援 PDF, DOCX, TXT)...": "Paste an article here, or upload a document above (PDF, DOCX, TXT)…",
  "測驗設定": "Quiz Settings",
  "發佈到 Bot": "Publish to Bot",
  "載入 Bot 中...": "Loading bots…",
  "暫無可用 Bot": "No Bots Available",
  "· 已分享": "· Shared",
  "這裡只顯示目前帳戶已分享的 Bot，並可選擇本次測驗要發佈到哪個教學角色。": "Only bots shared by the current account are shown. Select the teaching character to publish this quiz to.",
  "目標年級": "Target Grade",
  "小一至小三 (P1-P3)": "Primary 1–3 (P1–P3)",
  "小四至小六 (P4-P6)": "Primary 4–6 (P4–P6)",
  "中一至中三 (S1-S3)": "Secondary 1–3 (S1–S3)",
  "中四至中六 (S4-S6)": "Secondary 4–6 (S4–S6)",
  "題目數量": "Number of Questions",
  "這裡控制的是整份測驗的總題數。下一步後，AI 會根據目標年級與題目數量自動分配最適合的題型與內容。": "Set the total number of quiz questions. AI will choose suitable question types and content based on the grade and count.",
  "已導入草稿「": "Imported draft “",
  "」。確認內容後，請按下一步繼續編輯題目。": "”. Review the content, then select Next to continue editing.",
  "正在生成題目...": "Generating questions…",
  "下一步：預覽與儲存": "Next: Preview and Save",
  "下一步：預覽與發佈": "Next: Preview and Publish",
  "請選擇您最近使用過的文本材料：": "Select recently used text materials:",
  "選擇草稿後會載入完整題目，繼續預覽與編輯。": "Select a draft to load all questions and continue editing.",
  "目前沒有可導入的草稿": "No Drafts to Import",
  "未設定年級": "Grade Not Set",
  "多項選擇題": "Multiple Choice",
  "判斷題": "True / False",
  "簡答題": "Short Answer",
  "論述題": "Essay",
  "AI 測驗草稿": "AI Quiz Draft",
  "歷史題庫參考答案": "Historical Question Bank Reference Answer",
  "發佈測驗失敗，請稍後再試。": "Could not publish quiz. Please try again later.",
  "儲存草稿失敗，請稍後再試。": "Could not save draft. Please try again later.",
  "修改題型失敗，請稍後再試。": "Could not change question type. Please try again later.",
  "修改題目失敗，請稍後再試。": "Could not update question. Please try again later.",
  "載入題庫失敗，請稍後再試。": "Could not load question banks. Please try again later.",
  "加入題庫失敗，請稍後再試。": "Could not add to question bank. Please try again later.",
  "這道題已經在該題庫中了。": "This question is already in that question bank.",
  "題目已加入題庫。": "Question added to the question bank.",
  "請先輸入題庫名稱。": "Enter a question bank name first.",
  "建立題庫失敗，請稍後再試。": "Could not create question bank. Please try again later.",
  "✨ AI 已成功為您生成": "✨ AI successfully generated",
  "道題目": "questions",
  "✨ 來自歷史題庫": "✨ From Question Bank History",
  "修改中...": "Updating…",
  "確定更改": "Confirm Change",
  "編輯題目": "Edit Question",
  "題目內容": "Question Text",
  "選項內容": "Answer Options",
  "參考答案": "Reference Answer",
  "保存修改": "Save Changes",
  "添加到題庫": "Add to Question Bank",
  "新建題庫": "New Question Bank",
  "載入題庫中...": "Loading question banks…",
  "目前還沒有題庫，先建立第一個題庫吧。": "No question banks yet. Create your first one.",
  "輸入新題庫名稱...": "Enter a new question bank name…",
  "確認中...": "Confirming…",
  "➕ 從歷史題庫挑選題目 (混合出題)": "➕ Select Historical Questions (Mixed Quiz)",
  "展開其餘": "Expand Remaining",
  "測驗名稱": "Quiz Name",
  "輸入測驗名稱...": "Enter quiz name…",
  "預覽": "Preview",
  "已儲存草稿": "Draft Saved",
  "立即發佈": "Publish Now",
  "草稿已保留，回到智能評測首頁後會出現在草稿箱。": "Your draft is saved and will appear on the Smart Assessment home page.",
  "挑選歷史題目": "Select Historical Questions",
  "搜尋題目內容或標籤...": "Search question text or tags…",
  "已選擇": "Selected",
  "加入至當前測驗": "Add to Current Quiz",
  "學生端視角預覽：": "Student View Preview:",
  "退出預覽": "Exit Preview",
  "請在此輸入你的答案...": "Enter your answer here…",
  "0 / 500 字": "0 / 500 characters",
  "提交試卷": "Submit Quiz",
  "寫實風格": "Realistic",
  "手繪風格": "Hand-drawn",
  "卡通風格": "Cartoon",
  "拖拽文件到此處": "Drag a file here",
  "或": "or",
  "選擇文件": "Choose File",
  "風格重塑中，請稍候...": "Restyling, please wait…",
  "已上傳圖片，確認後可直接使用。": "Image uploaded. Confirm to use it.",
  "使用原圖": "Use Original Image",
  "編輯背景圖": "Edit Background Image",
  "模板": "Templates",
  "自由": "Freeform",
  "裁剪背景圖": "Crop Background Image",
  "應用中...": "Applying…",
  "調整裁剪框": "Adjust Crop Area",
  "縮放": "Zoom",
  "自由模式：拖動裁剪框邊緣或角點調整範圍，圖片保持不動。": "Freeform mode: drag the crop edges or corners to resize the area. The image stays in place.",
  "為您的 AI 機器人命名": "Name Your AI Bot",
  "一個好名字是偉大旅程的開始。": "A great name is the start of a great journey.",
  "機器人名稱": "Bot Name",
  "例如：數學解題小能手": "e.g. Math Problem Solver",
  "未設定": "Not Set",
  "網址解析失敗": "Could not parse URL",
  "我會根據你提供的資料進行回答與整理。": "I will answer and organize information based on the materials you provide.",
  "未命名文件": "Untitled File",
  "知識解析失敗:": "Knowledge parsing failed:",
  "解析失敗，請重試。": "Parsing failed. Please try again.",
  "- 目前未能整理內容\n- 請檢查 API 設定或稍後重試": "- Could not organize the content\n- Check your API settings or try again later",
  "缺少內容": "Content Required",
  "請先輸入知識點內容。": "Enter knowledge-point content first.",
  "支援 PDF、DOC、DOCX，可一次上傳多個文件": "Supports PDF, DOC, and DOCX. Upload multiple files at once.",
  "個文件": "files",
  "解析": "Parse",
  "貼上需要解析的內容…": "Paste content to parse…",
  "資料解析": "Parsing Data",
  "重點抽取": "Extracting Key Points",
  "索引建立": "Building Index",
  "入庫完成": "Saved to Knowledge Base",
  "正在為您提取知識庫內容...": "Extracting knowledge-base content…",
  "系統處理進度": "Processing Progress",
  "實時處理日誌": "Live Processing Log",
  "• 內容載入中...": "• Loading content…",
  "• 正在解析段落結構...": "• Parsing paragraph structure…",
  "• 正在抽取知識重點...": "• Extracting key knowledge…",
  "友善、專業、可互動": "Friendly, professional, and interactive",
  "可根據知識庫進行對話回答": "Answer questions using the knowledge base",
  "已完成知識點抽取": "Knowledge extraction completed",
  "聊天互動、教學解説、問答輔助": "Chat, teaching explanations, and Q&A support",
  "人物名字": "Character Name",
  "未明確命名": "Not Named",
  "人物性格": "Personality",
  "核心能力": "Core Abilities",
  "關鍵知識": "Key Knowledge",
  "應用場景": "Use Cases",
  "知識內容": "Knowledge Content",
  "確認角色背景與摘要，再從關聯圖檢查知識結構。": "Confirm the character background and summary, then review the knowledge structure in the graph.",
  "已完成提取": "Extraction Complete",
  "清除並重新提取知識": "Clear and Extract Knowledge Again",
  "重新提取": "Extract Again",
  "來源：": "Source:",
  "未知來源": "Unknown Source",
  "人物背景設定": "Character Background Settings",
  "知識庫摘要": "Knowledge Base Summary",
  "知識庫架構": "Knowledge Base Structure",
  "切換視圖檢查知識點分類；列表視圖可調整層級或刪除項目。": "Switch views to review knowledge categories. Use list view to change levels or delete items.",
  "關聯圖": "Relationship Graph",
  "列表視圖": "List View",
  "中心節點": "Central Node",
  "人物": "Character",
  "（人物知識庫）": "(Character Knowledge Base)",
  "選取模式": "Selection Mode",
  "拖動畫布": "Pan Canvas",
  "回正圖譜": "Reset Graph",
  "人物知識庫": "Character Knowledge Base",
  "基礎事實 (": "Basic Facts (",
  "個)": "items)",
  "尚未補充説明": "No description added yet",
  "切換為深度理解": "Switch to Deep Understanding",
  "深度理解 (": "Deep Understanding (",
  "切換為基礎知識": "Switch to Basic Facts",
  "新增知識點": "Add Knowledge Point",
  "直接補充單一知識；新增後會立即出現在上方知識架構。": "Add a single knowledge point. It will appear in the structure above immediately.",
  "例如：人物背景": "e.g. Character Background",
  "知識層級": "Knowledge Level",
  "輸入完整説明，讓角色能準確理解並回答。": "Enter a full explanation so the character can understand and answer accurately.",
  "角色基礎": "Character Foundations",
  "這些設定會套用到所有主題，維持角色個性與回答方式一致。": "These settings apply to all topics to maintain a consistent personality and response style.",
  "學科分類": "Subject",
  "必選": "Required",
  "請選擇學科分類，未選擇將無法完成設定": "Select a subject to complete the setup",
  "角色性格（可多選）": "Personality (Select Multiple)",
  "嚴謹": "Rigorous",
  "幽默": "Humorous",
  "温柔": "Gentle",
  "直接": "Direct",
  "理性": "Rational",
  "熱情": "Enthusiastic",
  "活潑": "Lively",
  "西洋": "Western",
  "口語": "Conversational",
  "引導式": "Guided",
  "正式": "Formal",
  "親切對話": "Friendly Conversation",
  "簡潔": "Concise",
  "回答模式": "Answer Mode",
  "直接給答案": "Give Answers Directly",
  "不直接給答案": "Do Not Give Answers Directly",
  "知識提取模型": "Knowledge Extraction Model",
  "提取前可先選擇要使用的模型": "Choose a model before extraction",
  "上傳文件": "Upload Files",
  "導入網址": "Import URL",
  "貼上文字": "Paste Text",
  "upload-image 無回傳 url": "Image upload returned no URL",
  "背景上傳失敗，改用本地預覽圖：": "Background upload failed; using a local preview:",
  "頭像上傳失敗，改用本地預覽圖：": "Avatar upload failed; using a local preview:",
  "點擊或拖曳圖片上傳": "Click or drag an image to upload",
  "建議使用 3D 全身角色圖片，效果會更自然。": "A full-body 3D character image is recommended for natural-looking results.",
  "預設角色": "Default Character",
  "2. 形象與背景": "2. Appearance and Background",
  "設定 AI 機器人的外觀和聊天背景，讓互動更具吸引力。": "Set your AI bot's appearance and chat background for engaging interactions.",
  "背景設定": "Background Settings",
  "背景生成已用完": "Background Generation Allowance Used Up",
  "編輯背景": "Edit Background",
  "發布後生成可分享連結": "Publish to Generate a Share Link",
  "5. 安全與權限": "5. Safety and Permissions",
  "設定機器人的使用對象與內容安全級別，保護學生安全。": "Set access and content safety levels to protect students.",
  "權限分享模式": "Sharing Permissions",
  "特定羣組": "Specific Group",
  "僅限指定名單成員存取": "Only designated members can access",
  "任何擁有連結的人": "Anyone with the Link",
  "組織內使用者可憑連結存取": "Members of your organization can access via the link",
  "已複製": "Copied",
  "複製連結": "Copy Link",
  "安全過濾強度": "Content Filter Strength",
  "系統會自動過濾不適當內容，包括色情、暴力、歧視、自殘話題等": "The system filters inappropriate content, including sexual content, violence, discrimination, and self-harm topics",
  "標準": "Standard",
  "教育場景預設濾網，適度引導學生": "Default educational filter with appropriate guidance",
  "嚴格": "Strict",
  "偵測到敏感內容將停止回答": "Stop responding when sensitive content is detected",
  "自定義": "Custom",
  "輸入你額外想封鎖的詞彙": "Enter additional words to block",
  "例如：暴力, 色情, 烏煙瘴氣（使用逗號分隔）": "e.g. violence, explicit content (separate with commas)",
  "專業男主持": "Professional Male Host",
  "俊朗男友": "Charming Male Voice",
  "陽光男聲": "Cheerful Male Voice",
  "可愛男童": "Cute Boy",
  "抒情男聲": "Expressive Male Voice",
  "温和男聲": "Gentle Male Voice",
  "播報男聲": "Male Announcer",
  "活潑男聲": "Lively Male Voice",
  "温潤男聲": "Warm Male Voice",
  "電台男主播": "Male Radio Host",
  "聰明男童": "Clever Boy",
  "專業女主持": "Professional Female Host",
  "可愛女孩": "Cute Girl",
  "善良女聲": "Kind Female Voice",
  "温柔女聲": "Gentle Female Voice",
  "少女音色": "Young Female Voice",
  "少女音色-beta": "Young Female Voice - Beta",
  "少女音色（測試）": "Young Female Voice (Beta)",
  "成熟女性音色": "Mature Female Voice",
  "成熟女性音色-beta": "Mature Female Voice - Beta",
  "成熟女性音色（測試）": "Mature Female Voice (Beta)",
  "新聞女聲": "Female Newsreader",
  "清脆少女": "Clear Young Female Voice",
  "温暖少女": "Warm Young Female Voice",
  "甜美女聲": "Sweet Female Voice",
  "未命名聲線": "Unnamed Voice",
  "男聲": "Male Voice",
  "女聲": "Female Voice",
  "男童": "Boy",
  "女孩": "Girl",
  "新聞": "News",
  "主持": "Host",
  "温暖": "Warm",
  "柔和": "Soft",
  "甜美": "Sweet",
  "卡通": "Cartoon",
  "（測試）": "(Beta)",
  "標準聲線": "Standard Voice",
  "播報": "Announcer",
  "温": "Warm",
  "柔": "Soft",
  "可愛": "Cute",
  "童": "Child",
  "少女": "Young Female",
  "清脆": "Clear",
  "成熟": "Mature",
  "兒童": "Child",
  "青少年": "Teenager",
  "青年": "Young Adult",
  "成人": "Adult",
  "長者": "Senior",
  "建議先使用「全部」查看長者音色，之後再用關鍵字細篩。": "Select All to browse senior voices, then refine with keywords.",
  "搜尋聲線（名稱或關鍵字）": "Search voices by name or keyword",
  "全部年齡": "All Ages",
  "目前供應商未提供明確「長者」標記聲線，已自動顯示較成熟的替代音色。": "The provider does not explicitly label senior voices. Mature alternatives are shown instead.",
  "找不到符合的聲線，請換個關鍵字。": "No matching voices. Try another keyword.",
  "其他聲線": "Other Voices",
  "已選擇：": "Selected:",
  "未選擇聲線": "No Voice Selected",
  "你好，我係你嘅 AI 助手，好高興認識你。": "Hello, I am your AI assistant. Nice to meet you.",
  "去背失敗": "Could Not Remove Background",
  "Remove BG 處理失敗，請稍後再試。": "Background removal failed. Please try again later.",
  "上傳失敗": "Upload Failed",
  "影片上傳失敗，請稍後再試。": "Could not upload video. Please try again later.",
  "聲音預覽已用完": "Voice Preview Allowance Used Up",
  "試聽失敗": "Preview Failed",
  "聲音試聽失敗，請稍後再試。": "Could not preview voice. Please try again later.",
  "聲音製作": "Voice Creation",
  "試聽中…": "Previewing…",
  "試聽": "Preview Voice",
  "動畫設定": "Animation Settings",
  "開啟 AI 影片工作室": "Open AI Video Studio",
  "影片工作室任務失敗，重新打開後可再試一次。": "The Video Studio task failed. Reopen it to try again.",
  "影片正在背景生成中，你可以先繼續後面的步驟，稍後再回來查看進度。": "Videos are generating in the background. Continue with other steps and return to check progress later.",
  "待機動畫": "Idle Animation",
  "思考動畫": "Thinking Animation",
  "説話動畫": "Talking Animation",
  "上傳中": "Uploading",
  "未上傳": "Not Uploaded",
  "上傳影片": "Upload Video",
  "已選擇影片": "Video Selected",
  "尚未選擇檔案": "No File Selected",
  "正在上傳影片…": "Uploading video…",
  "無法載入主題內容": "Could not load topic content",
  "請輸入主題名稱。": "Enter a topic name.",
  "儲存失敗，請稍後再試。": "Could not save. Please try again later.",
  "無法重新載入主題內容": "Could not reload topic content",
  "這是目前的預設主題。刪除後，系統會自動把下一個主題設為預設，相關對話也會安全轉移。": "This is the default topic. Deleting it makes the next topic the default and safely transfers related conversations.",
  "相關對話會自動轉移至其餘主題，既有訊息不會被刪除。": "Related conversations will move to another topic. Existing messages will not be deleted.",
  "刪除主題": "Delete Topic",
  "刪除失敗，請稍後再試。": "Could not delete. Please try again later.",
  "主題版本": "Topic Versions",
  "發布角色後，可為不同教學情境建立獨立主題。": "After publishing, create separate topics for different teaching scenarios.",
  "主題版本會在角色首次發布後啟用": "Topic Versions Are Available After First Publication",
  "目前先完成角色的基礎知識；發布後再次編輯，即可新增最多四個獨立主題。": "Complete the character's core knowledge first. After publishing, edit it to add up to four independent topics.",
  "身份與説話風格保持一致；每個主題擁有獨立提示與背景知識。": "Identity and speaking style stay consistent; each topic has its own instructions and background knowledge.",
  "建立新主題": "Create New Topic",
  "每個角色最多可建立 4 個主題。": "Each character can have up to 4 topics.",
  "正在載入主題…": "Loading topics…",
  "角色主題列表": "Character Topics",
  "尚未加入主題説明": "No topic description added yet",
  "編輯": "Edit",
  "至少需要保留一個主題": "At Least One Topic Is Required",
  "新增主題": "Add Topic",
  "預設主題": "Default Topic",
  "主題設定": "Topic Settings",
  "建立主題": "Create Topic",
  "編輯中": "Editing",
  "僅供檢視": "View Only",
  "主題名稱": "Topic Name",
  "例如：閱讀理解": "e.g. Reading Comprehension",
  "主題説明": "Topic Description",
  "簡短説明這個主題能協助學生什麼。": "Briefly describe how this topic helps students.",
  "主題專屬提示": "Topic-specific Instructions",
  "描述此主題的教學目標、回答策略與限制。角色身份與基本風格會由系統保留。": "Describe the teaching goals, response strategies, and limits. The system preserves the character's identity and basic style.",
  "主題背景知識": "Topic Background Knowledge",
  "貼上只屬於這個主題的知識內容；切換主題後，其他主題的內容不會同時注入。": "Paste knowledge specific to this topic. Other topics' content is not included when switching here.",
  "設為預設主題": "Set as Default Topic",
  "新對話未指定主題時會自動使用": "Used automatically when a new conversation does not specify a topic",
  "儲存變更": "Save Changes",
  "點擊左側「編輯」後即可修改此主題。": "Select Edit on the left to modify this topic."
};
